name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Android SDK Command-Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          mkdir -p $HOME/sdk
          cd $HOME/sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d cmdline-tools-temp
          mkdir -p $HOME/sdk/cmdline-tools/latest
          mv cmdline-tools-temp/cmdline-tools/* $HOME/sdk/cmdline-tools/latest/
          rm -rf cmdline-tools-temp
          
      - name: Set up sdkmanager path
        run: echo "$HOME/sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --upgrade pip
          pip3 install --user buildozer cython==0.29.33
          
      - name: Install Android SDK Build Tools
        run: |
         yes | sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools"    
      
      

      - name: Build with Buildozer
        run: |
          # Adding ~/.local/bin to PATH to find buildozer
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kanpurdepot-debug-apk
          path: bin/*.apk
